---
# Install docker-ce on Debian based OS
- debug: msg="play_hosts={{ play_hosts }}"
- debug: msg="ansible_distribution={{ ansible_distribution }}"

- name: remove possible old versions
  package:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: install dependencies
  package:
    name:
      - apt-transport-https
      - apt-transport-tor
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-pip
      - python3-pip
    state: present

    # - name: install python modules (for older versions of OS)
    #  pip:
    #    name:
    #    - urllib3
    #    - pyOpenSSL
    #    - ndg-httpsclient
    #    - pyasn1
    #    state: present
    #    executable: pip3

- name: Add docker key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present

- name: Add Docker CE APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker ce
  package:
    name: docker-ce
    state: present
